services:
  backend:
    image: ${CI_BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}
    container_name: neo-blog-backend
    restart: unless-stopped
    networks:
      - database-network
      - app-network

networks:
  database-network:
    external: true
  app-network:
    external: true
