services:
  blog-api:
    image: ${CI_REGISTRY}/${CI_PROJECT}/${CI_SERVICE}:${CI_TAG}
    restart: unless-stopped
    networks:
      - database-network
      - app-network

networks:
  database-network:
    external: true
  app-network:
    external: true
