services:
  blog-admin:
    image: ${CI_REGISTRY}/${CI_PROJECT}/${CI_SERVICE}:${CI_TAG}
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - app-network-prod

networks:
  app-network-prod:
    external: true